version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack-main}"
    image: localstack/localstack-pro  # required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
      - "127.0.0.1:8080:8080"              # LocalStack HTTP KubeContainers
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
    # - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # required for Pro
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_TRANSPARENT_ENDPOINT_INJECTION=0
      - DNS_LOCAL_NAME_PATTERNS=.*.cloudfront.net
      - AWS_DEFAULT_REGION=us-east-1
        
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${HOME}/.kube/config:/root/.kube/config"
